#!/usr/bin/env python

from bugwar_api import *
from sys import argv
from sys import stdout

url = None

if len(argv) >= 2:
	battery_name = argv[1]
	if len(argv) == 3:
		url = argv[2]
	salvo = start(battery_name)
	salvo.url = url
	salvo.save()
	print salvo.id,
else:
	print "usage: bugwar_start battery_name [url]"
	exit(1)

